# Generated by Django 5.1.4 on 2024-12-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_menusalads_image_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuhotter',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
